# -*- coding: utf-8 -*-

print ("module [backend_model.table_typhoon.py] loaded")
from backend_model.table_school import *
#db = DBManager.db


class Typhoons(db.Model):
    __tablename__ = 'tb_typhoon_info'
    id = db.Column('id', db.Integer, primary_key=True, autoincrement=True)
    typhoon_number = db.Column('typhoon_number', db.String(50), primary_key=True)
    typhoon_name = db.Column('typhoon_name', db.String(50))
    typhoon_start_date = db.Column('typhoon_start_date', db.DateTime)
    typhoon_end_date = db.Column('typhoon_end_date', db.DateTime)
    typhoon_dir = db.Column('typhoon_dir', db.String(10))
    typhoon_size = db.Column('typhoon_size', db.String(10))
    typhoon_v_type = db.Column('typhoon_v_type', db.Integer)
    fk_user_id = db.Column('fk_user_id', db.Integer)
    parent_typhoon_id = db.Column('parent_typhoon_id', db.Integer,default=-1)


class Paths(db.Model):
    __tablename__ = 'tb_typhoon_path'
    id = db.Column('id', db.Integer, primary_key=True)
    created_date = db.Column('created_date', db.DateTime)
    latitude = db.Column('latitude', db.Float)
    longitude = db.Column('longitude', db.Float)
    center_pressure = db.Column('center_pressure', db.Integer)
    max_speed_s = db.Column('max_speed_s', db.Integer)
    max_speed_h = db.Column('max_speed_h', db.Integer)
    wind_radius = db.Column('wind_radius', db.Integer)
    storm_radius = db.Column('storm_radius', db.String(50))
    strength = db.Column('strength', db.String(50))
    direction = db.Column('direction', db.String(50))
    move_speed_h = db.Column('move_speed_h', db.Integer)
    modify_date = db.Column('modify_date', db.Integer)
    fk_typhoon_id = db.Column('fk_typhoon_id', db.Integer, db.ForeignKey(Typhoons.id))
    typhoon = db.relationship('Typhoons')


class Accidents(db.Model):
    __tablename__ = 'tb_typhoon_acci_info'
    id = db.Column('id', db.Integer, primary_key=True)
    acci_number = db.Column('acci_number', db.String(50))
    acci_year = db.Column('acci_year', db.String(50))
    sub_group_id = db.Column('sub_group_id', db.String(50))
    school_name = db.Column('school_name', db.String(50))
    school_number = db.Column('school_number', db.String(50))
    school_type = db.Column('school_type', db.String(50))
    school_address = db.Column('school_address', db.String(100))
    latitude = db.Column('latitude', db.Float)
    longitude = db.Column('longitude', db.Float)
    acci_occu_date = db.Column('acci_occu_date', db.String(50))
    damage_desc = db.Column('damage_desc', db.String(255))
    precipitation = db.Column('precipitation', db.Float)
    temperature = db.Column('temperature', db.Float)
    wind_speed = db.Column('wind_speed', db.Float)
    typhoon_name = db.Column('typhoon_name', db.String(50))
    total_cost = db.Column('total_cost', db.Integer, default=0)
    establish_gubun_name = db.Column('establish_gubun_name', db.String(50))
    fk_typhoon_id = db.Column('fk_typhoon_id', db.Integer, db.ForeignKey(Typhoons.id))
    typhoon = db.relationship('Typhoons')
    fk_school_id = db.Column('fk_school_id', db.Integer, db.ForeignKey(SubSchools.id))
    school = db.relationship('SubSchools')
    fk_sub_group_id = db.Column('fk_sub_group_id', db.String(50), db.ForeignKey(SubGroups.id))
    subgroups = db.relationship('SubGroups')
    fk_area_id = db.Column('fk_area_id', db.Integer, db.ForeignKey(Areas.id))
    s3_data_json = db.Column('s3_data_json', db.String(4096))
    area = db.relationship('Areas')


class Deeps(db.Model):
    __tablename__ = 'tb_typhoon_deep_info'
    id = db.Column('id', db.Integer, primary_key=True)
    school_name = db.Column('school_name', db.String(50))
    school_number = db.Column('school_number', db.String(50))
    school_type = db.Column('school_type', db.String(50))
    school_address = db.Column('school_address', db.String(100))
    latitude = db.Column('latitude', db.Float)
    longitude = db.Column('longitude', db.Float)
    fk_typhoon_path_id = db.Column('fk_typhoon_path_id', db.Integer, db.ForeignKey(Paths.id))
    path = db.relationship('Paths')
    fk_typhoon_id = db.Column('fk_typhoon_id', db.Integer, db.ForeignKey(Typhoons.id))
    typhoon = db.relationship('Typhoons')


class TB_TYPOONREPORT(db.Model):
    __tablename__ = 'tb_typhoon_acci_report'
    id = db.Column('id', db.Integer, primary_key=True)
    inputyear = db.Column('inputyear', db.String(10))
    regional_code = db.Column('regional_code', db.String(20))
    area_code = db.Column('area_code', db.String(20))
    serial_num = db.Column('serial_num', db.Integer)
    disaster_num = db.Column('disaster_num', db.String(30))
    parent_disaster_num = db.Column('parent_disaster_num', db.String(30))
    disaster_gubun = db.Column('disaster_gubun', db.String(20))
    mem_name = db.Column('mem_name', db.String(30))
    mem_num = db.Column('mem_num', db.String(100))
    school_name = db.Column('school_name', db.String(100))
    school_code = db.Column('school_code', db.String(50))
    school_num = db.Column('school_num', db.String(50))
    structure_code = db.Column('structure_code', db.String(50))
    establish_gubun = db.Column('establish_gubun', db.String(20))
    organ_gubun1 = db.Column('organ_gubun1', db.String(20))
    organ_gubun2 = db.Column('organ_gubun2', db.String(50))
    organ_gubun2_etc = db.Column('organ_gubun2_etc', db.String(250))
    organ_gubun2_group = db.Column('organ_gubun2_group', db.String(50))
    zonecode = db.Column('zonecode', db.String(10))
    sido_name = db.Column('sido_name', db.String(20))
    addr1 = db.Column('addr1', db.String(100))
    addr2 = db.Column('addr2', db.String(100))
    lat = db.Column('lat', db.String(20))
    lng = db.Column('lng', db.String(20))
    approval_status = db.Column('approval_status', db.String(20))
    process_status = db.Column('process_status', db.String(20))
    display_yn = db.Column('display_yn', db.String(20))
    createname = db.Column('createname', db.String(30))
    createid = db.Column('createid', db.String(30))
    createdate = db.Column('createdate', db.String(20))
    updatename = db.Column('updatename', db.String(30))
    updateid = db.Column('updateid', db.String(30))
    updatedate = db.Column('updatedate', db.String(20))
    approval1_id = db.Column('approval1_id', db.String(20))
    approval1_date = db.Column('approval1_date', db.String(20))
    approval2_id = db.Column('approval2_id', db.String(30))
    approval2_date = db.Column('approval2_date', db.String(20))
    create_no = db.Column('create_no', db.Integer)
    update_no = db.Column('update_no', db.Integer)
    org_regional_code = db.Column('org_regional_code', db.String(20))
    org_area_code = db.Column('org_area_code', db.String(20))
    org_disaster_num = db.Column('org_disaster_num', db.String(100))
    delete_yn = db.Column('delete_yn', db.String(1))
    commission_status = db.Column('commission_status', db.String(10))
    area_code_name = db.Column('area_code_name', db.String(20))
    regional_code_name = db.Column('regional_code_name', db.String(20))
    disaster_gubun_name = db.Column('disaster_gubun_name', db.String(20))
    establish_gubun_name = db.Column('establish_gubun_name', db.String(20))
    organ_gubun2_name = db.Column('organ_gubun2_name', db.String(20))
    sub2_sdate = db.Column('sub2_sdate', db.String(20))
    sub2_accept_date1 = db.Column('sub2_accept_date1', db.String(20))
    sub2_enquiry_date1 = db.Column('sub2_enquiry_date1', db.String(20))
    sub2_enquiry_name = db.Column('sub2_enquiry_name', db.String(20))
    sub2_damage_detail = db.Column('sub2_damage_detail', db.String(20))
    sub2_data1 = db.Column('sub2_data1', db.String(20))
    sub2_data2 = db.Column('sub2_data2', db.String(20))
    sub2_data3 = db.Column('sub2_data3', db.String(20))
    sub2_data4 = db.Column('sub2_data4', db.String(20))
    sub2_data5 = db.Column('sub2_data5', db.String(20))
    sub2_data6 = db.Column('sub2_data6', db.String(20))
    sub2_disaster_cause = db.Column('sub2_disaster_cause', db.String(20))
    sub2_fire_stime = db.Column('sub2_fire_stime', db.String(20))
    sub2_fire_etime = db.Column('sub2_fire_etime', db.String(20))
    sub2_fire_cause = db.Column('sub2_fire_cause', db.String(20))
    sub2_disaster_cause_etc = db.Column('sub2_disaster_cause_etc', db.String(20))
    sub2_disaster_naming = db.Column('sub2_disaster_naming', db.String(20))
    sub2_recom_person_yn = db.Column('sub2_recom_person_yn', db.String(20))
    sub2_recom_obj_yn = db.Column('sub2_recom_obj_yn', db.String(20))
    sub2_enquiry_date2 = db.Column('sub2_enquiry_date2', db.String(20))
    sub2_enquiry_date3 = db.Column('sub2_enquiry_date3', db.String(20))
    sub2_enquiry_date4 = db.Column('sub2_enquiry_date4', db.String(20))
    sub2_enquiry_date5 = db.Column('sub2_enquiry_date5', db.String(20))
    sub2_enquiry_date6 = db.Column('sub2_enquiry_date6', db.String(20))
    sub2_enquiry_date7 = db.Column('sub2_enquiry_date7', db.String(20))
    sub2_enquiry_date8 = db.Column('sub2_enquiry_date8', db.String(20))
    sub2_enquiry_date9 = db.Column('sub2_enquiry_date9', db.String(20))
    sub2_enquiry_date10 = db.Column('sub2_enquiry_date10', db.String(20))
    sub2_modify_history = db.Column('sub2_modify_history', db.String)
    sub4_doc_accept_date = db.Column('sub4_doc_accept_date', db.String(20))
    sub4_doc_supplement_date1 = db.Column('sub4_doc_supplement_date1', db.String(20))
    sub4_doc_supplement_date2 = db.Column('sub4_doc_supplement_date2', db.String(20))
    sub4_doc_supplement_date3 = db.Column('sub4_doc_supplement_date3', db.String(20))
    sub4_doc_supplement_date4 = db.Column('sub4_doc_supplement_date4', db.String(20))
    sub4_doc_supplement_date5 = db.Column('sub4_doc_supplement_date5', db.String(20))
    sub4_doc_supplement_date6 = db.Column('sub4_doc_supplement_date6', db.String(20))
    sub4_doc_supplement_date7 = db.Column('sub4_doc_supplement_date7', db.String(20))
    sub4_doc_supplement_date8 = db.Column('sub4_doc_supplement_date8', db.String(20))
    sub4_doc_supplement_date9 = db.Column('sub4_doc_supplement_date9', db.String(20))
    sub4_doc_supplement_date10 = db.Column('sub4_doc_supplement_date10', db.String(20))
    sub4_transfer_date = db.Column('sub4_transfer_date', db.String(20))
    sub4_delay_date = db.Column('sub4_delay_date', db.String(20))
    sub4_delay_date_reason = db.Column('sub4_delay_date_reason', db.String(20))
    sub4_area_damdang = db.Column('sub4_area_damdang', db.String(20))
    sub4_head_damdang = db.Column('sub4_head_damdang', db.String(20))
    sub4_son_com_name = db.Column('sub4_son_com_name', db.String(20))
    sub4_son_consign_date = db.Column('sub4_son_consign_date', db.String(20))
    sub4_son_consign_damdang = db.Column('sub4_son_consign_damdang', db.String(20))
    sub4_son_report_date = db.Column('sub4_son_report_date', db.String(20))
    sub4_son_end_report_date = db.Column('sub4_son_end_report_date', db.String(20))
    sub4_son_jamun_date = db.Column('sub4_son_jamun_date', db.String(20))
    sub4_jamun_com = db.Column('sub4_jamun_com', db.String(20))
    sub4_janjon_com = db.Column('sub4_janjon_com', db.String(20))
    sub4_janjon_goods = db.Column('sub4_janjon_goods', db.String(20))
    sub4_janjon_bid_money = db.Column('sub4_janjon_bid_money', db.String(20))
    sub4_janjon_susu = db.Column('sub4_janjon_susu', db.String(20))
    sub4_janjon_tax = db.Column('sub4_janjon_tax', db.String(20))

    sub6_payment_yn = db.Column('sub6_payment_yn', db.String(50))
    sub6_non_payment = db.Column('sub6_non_payment', db.String(50))
    sub6_non_payment_etc = db.Column('sub6_non_payment_etc', db.String(50))
    sub6_gubun1 = db.Column('sub6_gubun1', db.String(50))
    sub6_gubun234 = db.Column('sub6_gubun234', db.String(50))
    sub6_gubun5 = db.Column('sub6_gubun5', db.String(50))
    sub6_gubun6 = db.Column('sub6_gubun6', db.String(50))
    sub6_gubun7 = db.Column('sub6_gubun7', db.String(50))
    sub6_gubun8 = db.Column('sub6_gubun8', db.String(50))
    sub6_gubun910 = db.Column('sub6_gubun910', db.String(50))
    sub6_gubun11 = db.Column('sub6_gubun11', db.String(50))
    sub6_payment_date = db.Column('sub6_payment_date', db.String(50))
    sub6_total_req_money = db.Column('sub6_total_req_money', db.Integer)
    sub6_total_payment_money = db.Column('sub6_total_payment_money', db.Integer)
    sub6_total_reduce_money = db.Column('sub6_total_reduce_money', db.Integer)
    sub6_etc = db.Column('sub6_etc', db.String(50))
    sub6_son_susu = db.Column('sub6_son_susu', db.String(50))
    sub6_son_cost = db.Column('sub6_son_cost', db.String(50))
    sub6_son_susu_etc = db.Column('sub6_son_susu_etc', db.String(50))
    sub6_son_score = db.Column('sub6_son_score', db.String(50))
    sub6_gamsa_report_date = db.Column('sub6_gamsa_report_date', db.String(50))
    sub6_gamsa_return_date = db.Column('sub6_gamsa_return_date', db.String(50))
    sub6_gamsa_etc = db.Column('sub6_gamsa_etc', db.String(50))
    sub6_gongje_open_date = db.Column('sub6_gongje_open_date', db.String(50))
    sub6_gongje_etc = db.Column('sub6_gongje_etc', db.String(50))
    sub6_jigub_gongje_date = db.Column('sub6_jigub_gongje_date', db.String(50))
    sub6_jigub_period = db.Column('sub6_jigub_period', db.String(50))
    sub6_jigub_sonsa_date = db.Column('sub6_jigub_sonsa_date', db.String(50))
    sub6_jigub_gongmun_date = db.Column('sub6_jigub_gongmun_date', db.String(50))
    sub6_gubun12 = db.Column('sub6_gubun12', db.String(50))
    sub6_gubun13 = db.Column('sub6_gubun13', db.String(50))
    sub6_gubun14 = db.Column('sub6_gubun14', db.String(50))
    sub6_total_payment_text = db.Column('sub6_total_payment_text', db.String(50))
    sub6_gubun15 = db.Column('sub6_gubun15', db.String(50))
    sub6_gubun16 = db.Column('sub6_gubun16', db.String(50))
    sub6_gubun17 = db.Column('sub6_gubun17', db.String(50))
    sub6_gubun18 = db.Column('sub6_gubun18', db.String(50))
    sub6_gubun19 = db.Column('sub6_gubun19', db.String(50))
    sub6_gubun20 = db.Column('sub6_gubun20', db.String(50))
    sub6_gubun21 = db.Column('sub6_gubun21', db.String(50))
    sub6_gubun22 = db.Column('sub6_gubun22', db.String(50))
    sub6_gubun23 = db.Column('sub6_gubun23', db.String(50))

    sdate = db.Column('sdate', db.String(20))
    disaster_cause = db.Column('disaster_cause', db.String(50))
    accept_date1 = db.Column('accept_date1', db.String(20))
    enquiry_date1 = db.Column('enquiry_date1', db.String(20))
    doc_accept_date = db.Column('doc_accept_date', db.String(20))
    doc_supplement_date1 = db.Column('doc_supplement_date1', db.String(20))
    doc_supplement_date2 = db.Column('doc_supplement_date2', db.String(20))
    doc_supplement_date3 = db.Column('doc_supplement_date3', db.String(20))
    doc_supplement_date4 = db.Column('doc_supplement_date4', db.String(20))
    doc_supplement_date5 = db.Column('doc_supplement_date5', db.String(20))
    doc_supplement_date6 = db.Column('doc_supplement_date6', db.String(20))
    doc_supplement_date7 = db.Column('doc_supplement_date7', db.String(20))
    doc_supplement_date8 = db.Column('doc_supplement_date8', db.String(20))
    doc_supplement_date9 = db.Column('doc_supplement_date9', db.String(20))
    doc_supplement_date10 = db.Column('doc_supplement_date10', db.String(20))
    transfer_date = db.Column('transfer_date', db.String(20))
    jigub_gongmun_date = db.Column('jigub_gongmun_date', db.String(20))
    payment_date = db.Column('payment_date', db.String(20))
    total_payment_money = db.Column('total_payment_money', db.Integer)
    gubun_max = db.Column('gubun_max', db.Integer)
    basefile1 = db.Column('basefile1', db.String(200))
    image_path1 = db.Column('image_path1', db.String(200))
    image_path2 = db.Column('image_path2', db.String(200))
    image_path3 = db.Column('image_path3', db.String(200))
    image_path4 = db.Column('image_path4', db.String(200))
    image_path5 = db.Column('image_path5', db.String(200))
    image_path6 = db.Column('image_path6', db.String(200))
    image_path7 = db.Column('image_path7', db.String(200))
    image_path8 = db.Column('image_path8', db.String(200))
    image_file_path1 = db.Column('image_file_path1', db.String(200))
    image_file_path2 = db.Column('image_file_path2', db.String(200))
    image_file_path3 = db.Column('image_file_path3', db.String(200))
    image_file_path4 = db.Column('image_file_path4', db.String(200))
    image_file_path5 = db.Column('image_file_path5', db.String(200))
    image_file_path6 = db.Column('image_file_path6', db.String(200))
    s3_data_json = db.Column('s3_data_json', db.String(4096))
    fk_typhoon_id = db.Column('fk_typhoon_id', db.Integer)
    fk_area_id = db.Column('fk_area_id', db.Integer)
    check = db.Column('check', db.Integer)

class TB_CODE_SET(db.Model):
    __tablename__ = 'code_set'
    no = db.Column('no', db.Integer, primary_key=True)
    code = db.Column('code', db.String(50))
    pcode = db.Column('pcode', db.String(50))
    gcode = db.Column('gcode', db.String(50))
    level = db.Column('level', db.String(10))
    name = db.Column('name', db.String(10))
    orderby = db.Column('orderby', db.Integer)
    display = db.Column('display', db.Integer)
    comment = db.Column('comment', db.String(250))
    gubun = db.Column('gubun', db.String(10))

class AccidentsPredict(db.Model):
    __tablename__ = 'tb_typhoon_acci_predict'
    id = db.Column('id', db.Integer, primary_key=True)
    mem_name = db.Column('mem_name', db.String(50))
    school_name = db.Column('school_name', db.String(50))
    area_code_name = db.Column('area_code_name', db.String(50))
    establish_gubun_name = db.Column('establish_gubun_name', db.String(50))
    organ_gubun2_name = db.Column('organ_gubun2_name', db.String(50))
    sub2_disaster_naming = db.Column('sub2_disaster_naming', db.String(50))
    total_payment_money = db.Column('total_payment_money', db.Integer, default=0)
    school_address = db.Column('school_address', db.String(100))
    latitude = db.Column('latitude', db.Float)
    longitude = db.Column('longitude', db.Float)
    acci_occu_date = db.Column('acci_occu_date', db.String(50))
    damage_desc = db.Column('damage_desc', db.String(255))
    precipitation = db.Column('precipitation', db.Float)
    temperature = db.Column('temperature', db.Float)
    wind_speed = db.Column('wind_speed', db.Float)
    fk_typhoon_id = db.Column('fk_typhoon_id', db.Integer, db.ForeignKey(Typhoons.id))
    typhoon = db.relationship('Typhoons')
    fk_school_id = db.Column('fk_school_id', db.Integer, db.ForeignKey(SubSchools.id))
    school = db.relationship('SubSchools')
    fk_area_id = db.Column('fk_area_id', db.Integer, db.ForeignKey(Areas.id))
    fk_user_id = db.Column('fk_user_id', db.Integer)
    sub_school_num = db.Column('sub_school_num', db.String(50))
    sub_group_num = db.Column('sub_group_num', db.String(50))
    area = db.relationship('Areas')


class Settings(db.Model):
    __tablename__ = 'tb_setting'
    id = db.Column('id', db.Integer, primary_key=True)
    created_date = db.Column('created_date', db.DateTime)
    modify_date = db.Column('modify_date', db.DateTime)
    smtp_server = db.Column('smtp_server', db.String(50))
    smtp_port = db.Column('smtp_port', db.String(50))
    smtp_sender = db.Column('smtp_sender', db.String(50))
    smtp_id = db.Column('smtp_id', db.String(50))
    smtp_pass = db.Column('smtp_pass', db.String(50))
